<?php

return array(
    'phpList\plugin\ContentAreas\ContentAreaBase' => $base . '/ContentAreas/ContentAreaBase.php',
    'phpList\plugin\ContentAreas\ContentAreaEditor' => $base . '/ContentAreas/ContentAreaEditor.php',
    'phpList\plugin\ContentAreas\ContentAreaHideable' => $base . '/ContentAreas/ContentAreaHideable.php',
    'phpList\plugin\ContentAreas\ContentAreaImage' => $base . '/ContentAreas/ContentAreaImage.php',
    'phpList\plugin\ContentAreas\ContentAreaPreheader' => $base . '/ContentAreas/ContentAreaPreheader.php',
    'phpList\plugin\ContentAreas\ContentAreaRepeat' => $base . '/ContentAreas/ContentAreaRepeat.php',
    'phpList\plugin\ContentAreas\ContentAreaText' => $base . '/ContentAreas/ContentAreaText.php',
    'phpList\plugin\ContentAreas\ContentAreaTextArea' => $base . '/ContentAreas/ContentAreaTextArea.php',
    'phpList\plugin\ContentAreas\ControllerFactory' => $base . '/ContentAreas/ControllerFactory.php',
    'phpList\plugin\ContentAreas\ConvertHtmlEntities' => $base . '/ContentAreas/ConvertHtmlEntities.php',
    'phpList\plugin\ContentAreas\CssInlinerFactory' => $base . '/ContentAreas/CssInlinerFactory.php',
    'phpList\plugin\ContentAreas\DAO' => $base . '/ContentAreas/DAO.php',
    'phpList\plugin\ContentAreas\EditorProvider' => $base . '/ContentAreas/EditorProvider.php',
    'phpList\plugin\ContentAreas\EditorProviderCK' => $base . '/ContentAreas/EditorProvider.php',
    'phpList\plugin\ContentAreas\EditorProviderFck' => $base . '/ContentAreas/EditorProvider.php',
    'phpList\plugin\ContentAreas\EditorProviderTiny' => $base . '/ContentAreas/EditorProvider.php',
    'phpList\plugin\ContentAreas\EmogrifierCssInliner' => $base . '/ContentAreas/CssInlinerFactory.php',
    'phpList\plugin\ContentAreas\Merger' => $base . '/ContentAreas/Merger.php',
    'phpList\plugin\ContentAreas\MessageController' => $base . '/ContentAreas/MessageController.php',
    'phpList\plugin\ContentAreas\MessageModel' => $base . '/ContentAreas/MessageModel.php',
    'phpList\plugin\ContentAreas\MethodNotImplementedException' => $base . '/ContentAreas/EditorProvider.php',
    'phpList\plugin\ContentAreas\NullCssInliner' => $base . '/ContentAreas/CssInlinerFactory.php',
    'phpList\plugin\ContentAreas\PreMailerCssInliner' => $base . '/ContentAreas/CssInlinerFactory.php',
    'phpList\plugin\ContentAreas\Reference' => $base . '/ContentAreas/Reference.php',
    'phpList\plugin\ContentAreas\TemplateModel' => $base . '/ContentAreas/TemplateModel.php',
    'phpList\plugin\ContentAreas\UnknownEditorException' => $base . '/ContentAreas/EditorProvider.php',
);
